apiVersion: v1
kind: Service
metadata:
  name: {{ include "percona_haproxy.fullname" . }}
  labels:
    {{- include "percona_haproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- include "percona_haproxy.selectorLabels" . | nindent 4 }}
